### PR TITLE
More fixes for JRuby

### PR DESCRIPTION
**Pull request by headius**
Various cross-platform fixes incoming.

### CODE REVIEW

**Comment by headius** [comment]
This is ready to merge and release. Among various cleanup fixes for the native logic, this also switches MacOS AArch64 to use the "stty" adapter that shells out rather than using FFI. This is a fairly big change, but given the ongoing bugs running on this platform, this is a significant improvement in that IRB with Reline works properly again.

The remaining bugs in the native FFI console logic still must be fixed on MacOS/AArch64 (and any other platforms). This is a temporary workaround to get users full IRB capability.

**Comment by headius** [comment]
@hsbt @nobu Can we get a release out with all latest patches? This would help our users that cannot currently use IRB + reline + io-console on MacOS/AArch64.

**Comment by hsbt** [comment]
@headius done! https://github.com/ruby/io-console/releases/tag/v0.7.2

**Comment by headius** [comment]
@hsbt Thank you! 🙏

**Pull request merged**
